version: '3'

services: 

  database:
    image: mysql
    restart: always
    networks:
      - devops-network
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=ppmtool
      - MYSQL_USER=ppmtool
      - MYSQL_PASSWORD=ppmtool
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql-volume/db:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    networks:
    - devops-network
    ports:
    - 8810:8080
    container_name: adminer

networks:
  devops-network: